name: speaker_embedding

channels:
- anaconda
- conda-forge
- pytorch

dependencies:
# Essential
- python==3.7.6
- numpy==1.18.1
- scipy==1.3.1
- pandas==0.25.3
- tqdm==4.41.1
- pip==19.3
# Visualization
- matplotlib==3.1.2
- umap-learn==0.3.10
# ML & DL
- scikit-learn==0.22
- pytorch==1.4.0
- torchaudio==0.4.0
# NLP & Speech
- librosa==0.7.2
# Jupyter integration
- nb_conda_kernels==2.2.2
- ipython==7.1.1
- ipywidgets==7.5.1

- pip:
  - jcopdl==1.1.0
